/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MeilleursArticlesRouteImport } from './routes/meilleurs-articles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MeilleursArticlesRoute = MeilleursArticlesRouteImport.update({
  id: '/meilleurs-articles',
  path: '/meilleurs-articles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/articles': typeof ArticlesRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/meilleurs-articles': typeof MeilleursArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/articles': typeof ArticlesRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/meilleurs-articles': typeof MeilleursArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/articles': typeof ArticlesRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/meilleurs-articles': typeof MeilleursArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/articles'
    | '/avis'
    | '/contact'
    | '/meilleurs-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/articles'
    | '/avis'
    | '/contact'
    | '/meilleurs-articles'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/articles'
    | '/avis'
    | '/contact'
    | '/meilleurs-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ArticlesRoute: typeof ArticlesRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  MeilleursArticlesRoute: typeof MeilleursArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meilleurs-articles': {
      id: '/meilleurs-articles'
      path: '/meilleurs-articles'
      fullPath: '/meilleurs-articles'
      preLoaderRoute: typeof MeilleursArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ArticlesRoute: ArticlesRoute,
  AvisRoute: AvisRoute,
  ContactRoute: ContactRoute,
  MeilleursArticlesRoute: MeilleursArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
